### ISSUE TITLE
Incorrect dyeing of blocks etc

### ISSUE THREAD

**Issue by RazzorX** [CoolLord22/OtherDrops3.1#4]
-- Many thanks for updating this plugin!
-- Sorry for my english...

If you use "od-dyewool.yml" (in folder "includes") or a custom version of this file, dyeing of blocks are not working correctly. If you use a red dye on white wool, the block changed in orange, if you use a blue dye, the block changed in yellow. Same with dyeing of carpets, glass etc.
Dyeing in craftingtable works correctly.

I hope you can fix this. Thanks.

**Comment by CoolLord22** [comment]
Confirmed issue, and I realize why it is happening. The @<Insert color here> tag pulls from the dye list. The dyes are actually reversed versions of blocks. For example, white wool data is 0, but bonemeal (white dye) data is 15. Black wool is 15, but black dye is 0. Because the ID's are reversed, it causes some issues with it. I would suggest not using @COLOR but rather use the item ID itself, such as 35@15 for black wool. I'll release a version that updates the includes file, you'll have to delete the old one so it can regenerate.

**Comment by CoolLord22** [comment]
@RazzorX Okay, so I fixed the issue with the dying of items, but noticed a new issue arise. Because of the offhand added in 1.9, the right-click event was being called twice (hence why things would be double-dying and gray wool would become white wool. It should go from gray to light gray then white, but because the event got called twice, it "skipped" the light gray. I patched this fix by disabling anything that is in the offhand, but this may cause issues for some other stuff. Could I have you test a private beta-version before I release it? 

It patches the double-right click but also stops handling for off-hand slot.

**Comment by RazzorX** [comment]
I have not found any issues! Now it's working like expected!
Thank you very much!

**Comment by CoolLord22** [comment]
Glad to hear 😄  If you have any other problems feel free to report them! ^-^

**Comment by CoolLord22** [comment]
@RazzorX Just to make sure, have you downloaded the Spigot version or the zip file? Be sure to download the latest from here: https://www.spigotmc.org/resources/otherdrops-updated.51793/history it includes the recent Vindicator fix!

**Comment by CoolLord22** [comment]
@RazzorX An update on this, if you took a look at commit
https://github.com/CoolLord22/OtherDrops/commit/38e3838b5c12c8e4d3fbf8eab1aaf07aaf48e283, the issue has been fixed there as well. Originally the plugin would subtract from 0xF resulting in the opposite colors. It works as expected (i.e. using `@RED` or `@WHITE` etc) but to ensure it works even further in the future, I'd suggest using the numbers.
